name: Prepare Staging for Production

on:
  push:
    branches:
      - staging

jobs:
  remove-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Remove __tests__ folder
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git rm -r __tests__ || true
          git commit -m "build: remove __tests__ folder for production" || echo "No tests folder to remove"

      - name: Remove testing libraries
        run: |
          git rm jest.config.ts || true
          git rm jest.setup.ts || true
          npm remove --save-dev @testing-library/jest-dom @testing-library/react @testing-library/user-event || true
          git commit -am "build: remove testing libraries for production" || echo "No testing libraries to remove"

      - name: Update package.json
        run: |
          npm pkg delete scripts.test
          npm pkg delete jest
          git commit -am "build: update package.json for production" || echo "No changes to package.json"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}